### ISSUE TITLE
RPC server freezes on sendTx with wrong permissions

### ISSUE THREAD

**Issue by containerman17** [ava-labs/hypersdk#1619] opened 2024-10-02 02:02 UTC
As I understood from a conversation with @owenwahlgren, the RPC server stops responding if sendTx is called involving an action that is missing one of the required state keys. After some time, it eventually responds with the error "expired." This needs confirmation.

This commit fixed the issue for cfmm: https://github.com/ava-labs/hypersdk-starter/commit/5bb9b2274ea60f837c4dce9bba0e269bcc2ec128

**Comment by owenwahlgren** [comment] 2024-10-02 13:35
+1
If state_manager.go doesn't have appropriate state keys the transaction will time out without an error.
If an action is missing required state keys it will return the expected error `invalid key or key permission`.

The state manager should throw an error similar to how actions do when missing state keys.

**Comment by containerman17** [comment] 2024-10-04 02:30
Confirmed. Reproduction steps for MorpheusVM:
1. Remove one of the required keys
```golang
func (t *Transfer) StateKeys(actor codec.Address) state.Keys {
	return state.Keys{
		string(storage.BalanceKey(actor)): state.Read | state.Write,
		string(storage.BalanceKey(t.To)):  state.All, // Remove this line 
	}
}
```
2. Run e2e test: `MODE=test ./scripts/run.sh`
3. Obsere the timeout

**Comment by containerman17** [comment] 2024-10-04 02:33
Confirmed. Reproduction steps for MorpheusVM:

1. Remove one of the required keys from `examples/morpheusvm/actions/transfer.go`:
```golang
func (t *Transfer) StateKeys(actor codec.Address) state.Keys {
	return state.Keys{
		string(storage.BalanceKey(actor)): state.Read | state.Write,
		// string(storage.BalanceKey(t.To)):  state.All, // Remove this line 
	}
}
```
2. Run e2e test: `MODE=test ./scripts/run.sh`
3. Observe the timeout:

```
/workspaces/Projects/ava-labs/hypersdk/examples/morpheusvm/tests/e2e/e2e_test.go:36
  Preparing configuration for new network with /home/vscode/.hypersdk/avalanchego-f03745d187d0c33b927121d4c8da977789b929ac/avalanchego
  Starting a single-node network with sybil protection disabled for quicker subnet creation
  Starting network /home/vscode/.tmpnet/networks/20241004-022825.453168-morpheusvm-e2e-tests (UUID: 6b4eaac9-84af-404f-ac04-a6d2ff9eaf75)
  [FAILED] in [SynchronizedBeforeSuite] - /go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:295 @ 10/04/24 02:28:35.7
[SynchronizedBeforeSuite] [FAILED] [10.507 seconds]
[SynchronizedBeforeSuite] 
/workspaces/Projects/ava-labs/hypersdk/examples/morpheusvm/tests/e2e/e2e_test.go:36

  [FAILED] 
        Error Trace:    /go/pkg/mod/github.com/ava-labs/avalanchego@v1.11.12-rc.2.0.20241001202925-f03745d187d0/tests/fixture/e2e/helpers.go:252
                                                /go/pkg/mod/github.com/ava-labs/avalanchego@v1.11.12-rc.2.0.20241001202925-f03745d187d0/tests/fixture/e2e/env.go:132
                                                /workspaces/Projects/ava-labs/hypersdk/tests/fixture/environment.go:40
                                                /workspaces/Projects/ava-labs/hypersdk/examples/morpheusvm/tests/e2e/e2e_test.go:57
                                                /usr/local/go/src/reflect/value.go:596
                                                /usr/local/go/src/reflect/value.go:380
                                                /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.1/internal/node.go:486
                                                /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.1/internal/suite.go:642
                                                /go/pkg/mod/github.com/onsi/ginkgo/v2@v2.13.1/internal/suite.go:889
                                                /usr/local/go/src/runtime/asm_arm64.s:1222
        Error:          failed to bootstrap network: %s
        Messages:       failed to start local node: failed to load process context for node "NodeID-7B5dkZw9SW3fWEt8iH31Q6xFZPmcy6o52" before timeout: context deadline exceeded
  
  In [SynchronizedBeforeSuite] at: /go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:295 @ 10/04/24 02:28:35.7
------------------------------
```

**Comment by RodrigoVillar** [comment] 2024-10-07 00:48
@containerman17 after following the steps you outlined, it seems that the error you posted above isn't related to the missing state keys issue, but rather is because of port conflicts. If you look at the logs for `NodeID-7B5dkZw9SW3fWEt8iH31Q6xFZPmcy6o52`, you should see the following error message:

```
[10-04|14:18:26.241] INFO node/node.go:952 initializing NAT
[10-04|14:18:26.241] INFO node/node.go:970 initializing API server
[10-04|14:18:26.241] FATAL app/app.go:75 failed to initialize node {"error": "couldn't initialize API server: listen tcp :9650: bind: address already in use"}
```

To reproduce this error message, you can run the following:

```
./scripts/run.sh`
MODE=test ./scripts/run.sh
```

**Comment by RodrigoVillar** [comment] 2024-10-07 00:50
@owenwahlgren can you give steps to reproduce the issue?

**Comment by containerman17** [comment] 2024-10-07 05:20
@RodrigoVillar, you’re right. The issue still needs confirmation.

**Comment by owenwahlgren** [comment] 2024-10-07 14:36
When we were using websockets:
https://github.com/ava-labs/hypersdk-starter-kit/commit/d77f72371fa4d0ebbdd2cff6d00b6d250fa098ea
Use same process: 
```docker compose pull && docker compose up -d --build devnet faucet frontend```
You may have to edit `const.ts` for correct ports.
Use a temporary key and attempt to Create Token, observe console.

**Comment by RodrigoVillar** [comment] 2024-10-07 19:48
@owenwahlgren for the `tx not found` error that you're encountering when using HTTP, this seems to be expected behavior

## Short Answer

The CreateToken TX is never being included in an accepted block. Since the TX indexer only indexes blocks that have been accepted (via `vm.processAcceptedBlock()`), attempting to query the block will result in an error

## Long Answer

The following logs provide context
```bash
[10-07|15:14:30.440] [0;0mINFO[0;0m <2rRgdtBYvHajcXVMbJt4aNYAC3Ro897mr3LhCQdbB818bK5tne Chain> vm/vm.go:975 valid transactions {"numTxs": 1, "txs": [{"base":{"timestamp":1728328529000,"chainId":"2rRgdtBYvHajcXVMbJt4aNYAC3Ro897mr3LhCQdbB818bK5tne","maxFee":10000000},"actions":[{"name":"Um9kcmlnb0NvaW4=","symbol":"UkM=","metadata":"Um9kcmlnbydzIGNvaW4="},{"to":"0x00c740c1f8b6cafdab549d9240ca0f3fe683ef3b4973fa58a81da66d839b7430ba","value":1000000000000000,"token":"0x03109740cefd40d84b46e007c17f21da6dfd58fca3e9b7cfa7aac1b22e36e4cd58"}],"auth":{"signer":[213,118,71,229,68,162,186,116,213,144,229,235,239,3,27,126,232,17,41,187,9,66,41,171,251,39,107,14,118,230,192,76],"signature":[105,120,44,152,73,178,55,156,91,231,31,238,19,38,118,195,9,210,94,122,157,181,18,112,5,215,147,81,238,1,33,33,29,243,0,47,191,11,35,76,30,127,2,220,111,144,25,228,199,169,249,191,100,29,36,163,103,157,196,92,52,237,86,7]}}]}
[10-07|15:14:30.449] DEBUG <2rRgdtBYvHajcXVMbJt4aNYAC3Ro897mr3LhCQdbB818bK5tne Chain> handler/handler.go:907 forwarding chan message to consensus {"messageOp": "notify"}
[10-07|15:14:30.449] [1;33mWARN[0;0m <2rRgdtBYvHajcXVMbJt4aNYAC3Ro897mr3LhCQdbB818bK5tne Chain> chain/builder.go:287 unexpected post-execution error {"error": "invalid key or key permission"}
[10-07|15:14:30.449] [1;33mWARN[0;0m <2rRgdtBYvHajcXVMbJt4aNYAC3Ro897mr3LhCQdbB818bK5tne Chain> chain/builder.go:342 build failed {"error": "invalid key or key permission"}
[10-07|15:14:30.449] DEBUG <2rRgdtBYvHajcXVMbJt4aNYAC3Ro897mr3LhCQdbB818bK5tne Chain> snowman/engine.go:658 failed building block {"error": "rpc error: code = Unknown desc = invalid key or key permission"}
```

In the above, we're submitting a transaction with the following action - `CreateToken(RodrigoCoin, RC, Rodrigo's Coin)`. This is handled by `vm.Submit()` which determines the transaction to be valid via `tx.PreExecute()`. This then eventually triggers `vm.BuildBlock()`; in this method, there's two important function calls being made:

- `tx.PreExecute()` 
- `tx.Execute()`

Recall that `tx.PreExecute()` said that our TX was valid and so `tx.Execute()` is the only wildcard left. With regards to `StateManager`, the biggest difference between these two functions is that `tx.PreExecute()` calls `CanDeduct()` while `tx.Execute()` calls `Deduct()`. In the context of the CFMM-VM, `CanDeduct()` only requires the state key of the sponsor's balance while `Deduct()` requires the state key of the sponsor's balance and the state key of the token info. By only specifying the state key of the sponsor's balance in `SponsorStateKeys()`, this leads to the case where `tx.PreExecute()` passes but `tx.Execute()` fails, thus leading to `BuildBlock()` failing as a whole.

Note that this is for HTTP, but I have a feeling that the same is also occurring for WS as well

**Comment by RodrigoVillar** [comment] 2024-10-09 14:17
After deep investigation, I propose that we close this issue as the RPC server hanging is expected and correct behavior (by hanging, I mean for any transaction `t` that is sent, it takes an usual amount of time to get a response regarding `t`).

As mentioned above, if `StateManager` is not implemented correctly, then any TXs sent to the VM will fail (in particular, the TX will cause an error in `vm.BuildBlock()`). Since this TX will never be put in an accepted block, it will never be indexed and therefore calling `getTX(t)` will return an error. 

Focusing back on the issue of hanging, the reason for this can be explained with the following (source: `hypersdk-client/src/client/index.ts`):

```ts
private async waitForTransaction(txId: string, timeout: number = 55000): Promise<TxResult> {
        const startTime = Date.now();
        let lastError: Error | null = null;
        for (let i = 0; i < 10; i++) {
            if (Date.now() - startTime > timeout) {
                throw new Error("Transaction wait timed out");
            }
            try {
                return await this.getTransactionStatus(txId);
            } catch (error) {
                lastError = error instanceof Error ? error : new Error(String(error));
                if (!(error instanceof Error) || error.message !== "tx not found") {
                    throw error;
                }
            }
            await new Promise(resolve => setTimeout(resolve, 100 * i));
        }
        throw lastError || new Error("Failed to get transaction status");
    }
```

When a client submits a TX with `hypersdk-client`, this code is responsible for getting the result of the submitted TX. Since calling `this.getTransactionStatus(txId)` will always return `ErrTxNotFound`, this for loop will either exhaust itself/time out and is therefore the reason for why the server hangs.

**Closed** 2024-10-09 16:06 UTC
